[package]
name = "texmath-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
lazy_static = "1.4.0"
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
ahash = "0.8.7"
log = "0.4.20"